baseURL = "/"
title = "mosf bvg"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
paginate = "7"
theme = "spectral-master"
publishDir = 'd:\github\mosf-bvg-Blog\docs'
# outdir = "docs"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "mosf bvg's blog" # title for frontpage, may include image
copyright = "mosf bvg"
description = '至此,已成bug'
# startbuttonText = "Activate"
# startbuttonLink = "#"
# body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
# images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

# [[params.one.icon]]
# icon = "fa-gem"
# style = "1"
# label = "Lorem"

# [[params.one.icon]]
# icon = "fa-heart"
# style = "2"
# label = "Ipsum"

# [[params.one.icon]]
# icon = "solid fa-code"
# style = "3"
# label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = '首先,这是一个废话'
body = '略'

[[params.two.section]]
img = "img/pic02.jpg"
title = '其次,这是一个废话'
body = '略'

[[params.two.section]]
img = "img/pic03.jpg"
title = '最后,这是一个废话'
body = '略'

# [params.three]
# enable = true
# title = 'Accumsan mus tortor nunc aliquet'
# body = '''
# Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
# fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
# '''

# [[params.three.feature]]
# icon = "fa-paper-plane"
# title = "Arcu accumsan"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [[params.three.feature]]
# icon = "solid fa-laptop"
# title = "Ac Augue Eget"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [[params.three.feature]]
# icon = "solid fa-code"
# title = "Foo bar"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [[params.three.feature]]
# icon = "solid fa-headphones-alt"
# title = "Baz kram"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [[params.three.feature]]
# icon = "fa-heart"
# title = "Some latin text"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [[params.three.feature]]
# icon = "fa-flag"
# title = "Nothing important"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

# [params.cta]
# enable = true
# title = "Arcue ut vel commodo"
# body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

# [[params.cta.link]]
# href = "#"
# text = "Activate"
# special = true

# [[params.cta.link]]
# href = "#"
# text = "Learn More"
# special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
# phone = "+86 (0) 11451411451"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
# email = "114@514.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.zh]
weight = 0
languageName = "Chinese"

[languages.en]
weight = 10
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
